name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        env:
          NEXT_PUBLIC_BASE_PATH: /portfolio   # <-- your repo name
        run: npm run build

      - name: Export static site
        env:
          NEXT_PUBLIC_BASE_PATH: /portfolio
        run: npm run build   # Next.js 14+ uses 'output: export', so build suffices

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out   # Next.js static export directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
